### ISSUE TITLE
Matlab only install on windows 7 (64)

### ISSUE THREAD

**Issue by andrewd01** [Statoil/segyio#180]
Hi, firstly thanks for developing segyio.  I am an experienced Matlab user but totally inexperienced with C coding, Cmake and C compilation in general.  I want to use segyio for Matlab only and need to use windows 7 (64 bit) since I am pulling input seismic data from Petrel to Matlab with the Matlab-Petrel link.  Matlab can read very large seismic files from Petrel (100 Gb+) and process very fast (key benefit is that it can access the Petrel seismic data directly without duplication, thereby avoiding segy export of many large files), but there is a bottleneck in writing the output data back to Petrel, hence my investigation of segyio.

I would very much appreciate some specific build instructions for a windows build, focussing on getting segyio running with Matlab. I downloaded Cmake, Codeblocks and MinGW add-on mex compiler for Matlab.  I found the GUI version of Cmake far more intuitive than the command line approach, but found a number of errors when trying to build segyio for Matlab only. 

 I configured my Matlab root directory in Cmake, but the build could not find the mex and mcc compilers.  I edited the cmake files to look for mex.bat instead of mex and it found them (could not find any other mex files in the matlab root/bin directory), but still not sure if this is correct.   I came across numerous other errors, too many to describe in detail here.

It would be hugely appreciated if some detailed instructions could be provided based on the Cmake gui version and a Matlab installation on windows 64.

**Comment by jokva** [comment]
Hi, Andrew, and thanks for your interest.

I'm not familiar with the cmake gui *at all*, so I'm afraid I can't be of much help there. You seem to be on the right track though, because if cmake can find your mex compiler (mex.bat sounds about right) you should be almost there.

All the matlab stuff, especially on Windows, is a bit rough because none of our developers use Windows (or matlab, really), so it doesn't get too much love.

Anywho, what you want to set in cmake is:

* BUILD_MEX to ON
* *Optional, but probably:* MATLAB_ROOT to your matlab install location.
* CMAKE_BUILD_TYPE to Release
* CMAKE_CXX_COMPILER to your MinGW install.

I'm afraid I can't give you anything more specific than that, because I'm not that familiar with matlab on Windows.

**Comment by jokva** [comment]
It could be helpful to post some of the error messages you get, because there might be some good hints in them

**Comment by andrewd01** [comment]
Thanks for the response.  I will post some of the specific error messages when I get back to trying this.  I see I can attach files here so I might capture some screen captures of the Cmake GUI as hopefully these will be helpful for other users trying to do what I am doing.  

Cheers,
Andrew

**Comment by jokva** [comment]
Sounds good, and it will probably be helpful for other people. Thanks!

**Comment by jokva** [comment]
While slightly unsatisfactory, nothing more will happen here, so I'm closing the issue.
