### ISSUE TITLE
Time/Horizon slice mode

### ISSUE THREAD

**Issue by stevejpurves** [Statoil/segyio#305]
Are there any plans for in-built time-slice retrieval? i.e. rather than iterating over traces in python, just getting a whole slice back via a sample (z) value?

and connected with that of course is being able to do the same on a horizon, providing an aligned [sub-]grid of sample (z) values as the index

If this feasible and/or planned? would you expect a performance from doing this at a low level? rather than someone writing an python convenience wrapper for segyio to so the same for example.

**Comment by jokva** [comment]
There's already a way to grab a time slice (fixed-z across the full grid), it's called `depth`. https://segyio.readthedocs.io/en/latest/segyio.html#depth

It should perform slightly better than hand-rolling your own, but there's still a *huge* penalty associated with this because of how segys are laid out.

> and connected with that of course is being able to do the same on a horizon, providing an aligned [sub-]grid of sample (z) values as the index

This is not implemented as-of now, but it's fairly easy to do on your own in a loop. There's no dedicated mode for it, and likely won't be, because the interface would be clunky and unpredictable.

**Comment by jokva** [comment]
That being said, `depth` is slightly problematic right now, and I'm not sure if we were wrong before, or if we're wrong now.

The problem is, when you extract your time (or depth) slice, you get an inline-by-crossline array. But which is the fast and slow dimension? Is it always in-by-cross, or is it fast-by-slow? That's a topic for it's own issue.

**Comment by stevejpurves** [comment]
awesome. I had completely missed the Depth indexing even though its been there since 1.1

and yes, implementing a loop at python level is easy enough. A lot of the manipulation is easy tbh with the features we already have, it's just something that's going to be written again and again by people...

is there a plan / space somewhere within the repo for that type python only utility/wrapper code. (segyio.contrib) or does that best live in a separate repo?

**Comment by jokva** [comment]
> and yes, implementing a loop at python level is easy enough. A lot of the manipulation is easy tbh with the features we already have, it's just something that's going to be written again and again by people...

Sure, which is why some of these features were developed and intended for mainline. Problem is _some_ of these extractions may sometimes have no actually always-right way to do it, and that way we can't do it.

**Comment by jokva** [comment]
> is there a plan / space somewhere within the repo for that type python only utility/wrapper code. (segyio.contrib) or does that best live in a separate repo?

Depends on scope, correctness, and quality, I suppose.

There's already `segyio.tools` which is intended for these "sometimes-useful-but-not-always" features. We could also add a third-party entry point `contrib`, so that packages can be developed and distributed independently of segyio, like with pytest.

**Comment by jokva** [comment]
Alright, so #307 should fix the shape issue. Once this is green and merged, I'll release 1.7.1 with all additional bugfixes in the merge queue.

**Comment by jokva** [comment]
For what it's worth, for _sufficiently_ small cubes, i.e. when they comfortably fit in memory, it's probably faster to read the full cube, and then use numpy indexing into that, at least if you end up querying multiple times.

**Comment by stevejpurves** [comment]
yes I tend to load there full cube when I often can on a workstation, but when you just want to extract maps or horizon relative slabs in order to pass it on or serve it out to something else, or are writing code that someone might try to use on a system with less resources then I prefer to avoid using cube.

good to know the intention with `tools`, tbh that is probably sufficient for small scale helper code like this.

**Comment by jokva** [comment]
I'll make a mental note of a `horizon` function, and see if we can figure out a good interface for it.

Until then, feel free to submit useful programs snippets for `tools`, or other nifty features if you can think of them.
