### ISSUE TITLE
Unable to Find sorting

### ISSUE THREAD

**Issue by lixiandea** [Statoil/segyio#309]
Unable to open segy files, these files can still be opened in the previous version. In this version there will be a“ cube_metrics = f.xfd.cube_metrics(iline, xline)” error, and all my segy files will get this error.
![default](https://user-images.githubusercontent.com/26404619/47151086-56d99080-d30b-11e8-9e52-7a347d7a7f47.png)

**Comment by lixiandea** [comment]
![image](https://user-images.githubusercontent.com/26404619/47152527-868a9780-d30f-11e8-9618-3c7663f96b95.png)

it's all zeros,but what ignore_geometry means?

**Comment by jokva** [comment]
If they're all zeros, that means your file *has* no geometry (at least in the rev1 sense, maybe they're located elsewhere).

`ignore_geometry` means that segyio will _not_ try to establish in/crosslines, and just give you access to the raw traces.

**Comment by lixiandea** [comment]
Ok,i got it, and if i try to get this,i have to set ignore_geometry , isn't it? But do you know other segy libraries as segyio?  And do you know the software "segyviewer"?

**Comment by jokva** [comment]
I'm afraid I don't understand the question, but to read files that _aren't_ properly sorted, that describe a single volume, you have to use `ignore_geometry`. This will disable some features because they're now nonsensical, but otherwise you get access to your data.

Some files have their in- and crossline information at different positions, 5 and 21 for in- and crossline respectively, is pretty common. You can make segyio aware of that by passing `iline = 5, xline = 21` to the `segyio.open` function.

segyviewer was written as a simple tool for quickly looking at seismic files, without having to do the dance with the complex setup of petrel and others.

**Comment by jokva** [comment]
It seems to me this issue is resolved now. If it isn't, feel free to repoen it or create a new issue.

**Comment by Aqsa-dev** [comment]
unable to find sorting.Check iline, (189) and xline (193) in case you are sure the file is a 3D sorted volume 
anyone help please
